### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by efancier-cn** [jimkring/nuitka-zig-cc#1]
I have a project and I use following command to compile it:
 python3 -m nuitka --standalone --output-dir=out --show-progress --onefile hello.py
How to use this script to enable zig as the cc compiler? could you please add some command line examples? Thank you!

**Comment by jimkring** [comment]
This is not working yet. You could look at the ci workflow yaml and shell scripts if you want to look at what it’s doing.

**Comment by jimkring** [comment]
@efancier-cn I was able to get it working.  You'll need to use the [latest nightly build of zig](https://ziglang.org/download/) (version 0.12.0-dev.3161+377ecc6af or newer).

Download the [zig-clang-cc.sh](https://github.com/jimkring/nuitka-zig-cc/blob/main/zig-clang-cc.sh) file and then configure the `CC` environment variable to be the absolute path to that script.  Then you can call nuitka (and be sure to pass the `--clang` option) like this:

```bash
# make the script executable
chmod ugo+x ./zig-clang-cc.sh

# set the CC environment variable to the absolute path of the script
export CC="$(pwd)/zig-clang-cc.sh"

# call nuikta and be sure to pass the `--clang` option
python -m nuitka --clang --standalone hello.py

# Note that Nuitka's `--standalone` option seems to be working
# However, the `--onefile` option does not work at the moment.
```

**Comment by efancier-cn** [comment]
Thank you, jimkring!
